// <auto-generated />
using System;
using Madibaz_Transit_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Madibaz_Transit_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904164114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ActiveQueues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TripId");

                    b.ToTable("ActiveQueues");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Announcements", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("FleetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusInspection", b =>
                {
                    b.Property<Guid>("BusInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("InspectedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRoadworthy")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusInspectionId");

                    b.HasIndex("BusId");

                    b.HasIndex("InspectedByUserId");

                    b.ToTable("BusInspection");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Heading")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusLocations");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TransitRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransitRouteId");

                    b.ToTable("BusStops");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ComplainTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TripId");

                    b.ToTable("ComplainTickets");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.DelayReport", b =>
                {
                    b.Property<Guid>("DelayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DelayId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripId");

                    b.ToTable("DelayReports");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DriverId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.DriverShift", b =>
                {
                    b.Property<Guid>("DriverShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverShiftId");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("DriverShifts");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.GPSCoordinateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("GPSCoordinateHistories");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IncidentId");

                    b.HasIndex("BusId");

                    b.HasIndex("TripId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.LostPropertyTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TripId");

                    b.ToTable("LostPropertyTickets");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Marshal", b =>
                {
                    b.Property<Guid>("MarshalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MarshalId");

                    b.HasIndex("UserId");

                    b.ToTable("Marshals");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("ShuttleId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.SeatReservations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BoardedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BoardingToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BoardingTokenUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BoardingTokenUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpiryReason")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VerifiedByAppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TripId");

                    b.ToTable("SeatReservations");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ShuttleAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarshalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("MarshalId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ShuttleAssignments");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ShuttleRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("ShuttleRequests");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.StudentProfiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.TransitRoute", b =>
                {
                    b.Property<Guid>("TransitRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransitRouteId");

                    b.ToTable("TransitRoutes");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<Guid>("DriverShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransitRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TripId");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverShiftId");

                    b.HasIndex("TransitRouteId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.TripStatusHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TripStatus")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("TripId");

                    b.ToTable("TripStatusHistories");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ActiveQueues", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany("ActiveQueues")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany("ActiveQueues")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.AppUser", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusInspection", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("BusInspections")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "InspectedByUser")
                        .WithMany()
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("InspectedByUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusLocation", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("BusLocations")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.BusStop", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.TransitRoute", "TransitRoute")
                        .WithMany("BusStops")
                        .HasForeignKey("TransitRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransitRoute");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ComplainTickets", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany("ComplaintTickets")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.DelayReport", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Driver", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany("Drivers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.DriverShift", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("DriverShifts")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Driver", "Driver")
                        .WithMany("DriverShifts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.TransitRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.GPSCoordinateHistory", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("GPSCoordinateHistories")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Incident", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("Incidents")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.LostPropertyTickets", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Marshal", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "User")
                        .WithMany("Marshals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Notifications", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.SeatReservations", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany("SeatReservations")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany("SeatReservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ShuttleAssignment", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("ShuttleAssignments")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Marshal", "Marshal")
                        .WithMany()
                        .HasForeignKey("MarshalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Marshal");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.ShuttleRequests", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.StudentProfiles", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.AppUser", "AppUser")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Trip", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.DriverShift", "DriverShift")
                        .WithMany()
                        .HasForeignKey("DriverShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.TransitRoute", "TransitRoute")
                        .WithMany()
                        .HasForeignKey("TransitRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("DriverShift");

                    b.Navigation("TransitRoute");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.TripStatusHistory", b =>
                {
                    b.HasOne("Madibaz_Transit_BackEnd.Models.Entities.Trip", "Trip")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.AppUser", b =>
                {
                    b.Navigation("ActiveQueues");

                    b.Navigation("ComplaintTickets");

                    b.Navigation("Drivers");

                    b.Navigation("Marshals");

                    b.Navigation("SeatReservations");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Bus", b =>
                {
                    b.Navigation("BusInspections");

                    b.Navigation("BusLocations");

                    b.Navigation("DriverShifts");

                    b.Navigation("GPSCoordinateHistories");

                    b.Navigation("Incidents");

                    b.Navigation("ShuttleAssignments");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Driver", b =>
                {
                    b.Navigation("DriverShifts");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.TransitRoute", b =>
                {
                    b.Navigation("BusStops");
                });

            modelBuilder.Entity("Madibaz_Transit_BackEnd.Models.Entities.Trip", b =>
                {
                    b.Navigation("ActiveQueues");

                    b.Navigation("SeatReservations");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
